apiVersion: apps/v1
kind: Deployment
metadata:
  name: min-ci-app
  labels:
    app: min-ci-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: min-ci-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25% 
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: min-ci-app
      spec:
        containers:
        - image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: min-ci-app
          ports:
          - containerPort: 3000
            protocol: TCP
