apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
