apiVersion: v1
kind: Service
metadata:
  name: runner
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: runner
  type: LoadBalancer
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
